### PR TITLE
Updates for dragonflight - still need to update options

### PR DESCRIPTION
**Pull request by Caerdon**
Things seem to be largely working - I haven't touched Settings panel so anything there will be broken.

### CODE REVIEW

**Comment by LutzFO** [comment]
Can you do a release for us (.zip)(others halls too)?
Tried here, but won't work.

**Comment by Caerdon** [comment]
I'll see if I can get something out as new addons for now and hopefully someone will come back and land this at some point.  I don't have any plans to actively support it other than make sure whatever is there manages to mostly work, though.

**Comment by Caerdon** [comment]
Sounds like the author is planning on pushing some updates out shortly, so I'll hold in hopes that those land!

**Comment by alar77** [comment]
Hi mate, I am on it

**Comment by alar77** [comment]
Used as a guideline but had to fix the whole thing

**Pull request closed without merging**
